// ---------------------------------------------------------------------------
// File        : pcie_versal_pcie_if_wrap.sv
// Description : Testbench wrapper presenting a Versal shaped boundary over the
//               PCIe library's interface module, so that module is exercised
//               through pcie_versal_adapt without being edited.
// Author      : Xiaohai Li <haixiaolee@gmail.com>
//
//
// Copyright (c) 2026 Xiaohai Li <haixiaolee@gmail.com>
// SPDX-License-Identifier: BSD-2-Clause-Views
// ---------------------------------------------------------------------------

`resetall
`timescale 1ns / 1ps
`default_nettype none

module pcie_versal_pcie_if_wrap #
(
    parameter AXIS_PCIE_DATA_WIDTH = 512,
    parameter AXIS_PCIE_KEEP_WIDTH = (AXIS_PCIE_DATA_WIDTH/32),
    parameter AXIS_PCIE_RC_USER_WIDTH = AXIS_PCIE_DATA_WIDTH < 512 ? 75 : 161,
    parameter AXIS_PCIE_RQ_USER_WIDTH = AXIS_PCIE_DATA_WIDTH < 512 ? 60 : 137,
    parameter AXIS_PCIE_CQ_USER_WIDTH = AXIS_PCIE_DATA_WIDTH < 512 ? 85 : 183,
    parameter AXIS_PCIE_CC_USER_WIDTH = AXIS_PCIE_DATA_WIDTH < 512 ? 33 : 81,
    parameter RC_STRADDLE = AXIS_PCIE_DATA_WIDTH >= 256,
    parameter RQ_STRADDLE = AXIS_PCIE_DATA_WIDTH >= 512,
    parameter CQ_STRADDLE = AXIS_PCIE_DATA_WIDTH >= 512,
    parameter CC_STRADDLE = AXIS_PCIE_DATA_WIDTH >= 512,
    parameter RQ_SEQ_NUM_WIDTH = AXIS_PCIE_RQ_USER_WIDTH == 60 ? 4 : 6,
    parameter TLP_DATA_WIDTH = AXIS_PCIE_DATA_WIDTH,
    parameter TLP_STRB_WIDTH = TLP_DATA_WIDTH/32,
    parameter TLP_HDR_WIDTH = 128,
    parameter TLP_SEG_COUNT = 1,
    parameter TX_SEQ_NUM_COUNT = AXIS_PCIE_DATA_WIDTH < 512 ? 1 : 2,
    parameter TX_SEQ_NUM_WIDTH = RQ_SEQ_NUM_WIDTH-1,
    parameter PF_COUNT = 1,
    parameter VF_COUNT = 0,
    parameter F_COUNT = PF_COUNT+VF_COUNT,
    parameter READ_EXT_TAG_ENABLE = 1,
    parameter READ_MAX_READ_REQ_SIZE = 1,
    parameter READ_MAX_PAYLOAD_SIZE = 1,
    parameter MSIX_ENABLE = 1,
    parameter MSI_ENABLE = 0,
    parameter MSI_COUNT = 32,
    parameter CPM5_RQ_USER_WIDTH = 183,
    parameter CPM5_CQ_USER_WIDTH = 231
)
(
    input  wire                                                      clk,
    input  wire                                                      rst,
    input  wire [AXIS_PCIE_DATA_WIDTH-1:0]                           s_axis_rc_tdata,
    input  wire [AXIS_PCIE_KEEP_WIDTH-1:0]                           s_axis_rc_tkeep,
    input  wire                                                      s_axis_rc_tvalid,
    output wire                                                      s_axis_rc_tready,
    input  wire                                                      s_axis_rc_tlast,
    input  wire [AXIS_PCIE_RC_USER_WIDTH-1:0]                        s_axis_rc_tuser,
    output wire [AXIS_PCIE_DATA_WIDTH-1:0]                           m_axis_rq_tdata,
    output wire [AXIS_PCIE_KEEP_WIDTH-1:0]                           m_axis_rq_tkeep,
    output wire                                                      m_axis_rq_tvalid,
    input  wire                                                      m_axis_rq_tready,
    output wire                                                      m_axis_rq_tlast,
    output wire [CPM5_RQ_USER_WIDTH-1:0]                             m_axis_rq_tuser,
    input  wire [AXIS_PCIE_DATA_WIDTH-1:0]                           s_axis_cq_tdata,
    input  wire [AXIS_PCIE_KEEP_WIDTH-1:0]                           s_axis_cq_tkeep,
    input  wire                                                      s_axis_cq_tvalid,
    output wire                                                      s_axis_cq_tready,
    input  wire                                                      s_axis_cq_tlast,
    input  wire [CPM5_CQ_USER_WIDTH-1:0]                             s_axis_cq_tuser,
    output wire [AXIS_PCIE_DATA_WIDTH-1:0]                           m_axis_cc_tdata,
    output wire [AXIS_PCIE_KEEP_WIDTH-1:0]                           m_axis_cc_tkeep,
    output wire                                                      m_axis_cc_tvalid,
    input  wire                                                      m_axis_cc_tready,
    output wire                                                      m_axis_cc_tlast,
    output wire [AXIS_PCIE_CC_USER_WIDTH-1:0]                        m_axis_cc_tuser,
    input  wire [RQ_SEQ_NUM_WIDTH-1:0]                               s_axis_rq_seq_num_0,
    input  wire                                                      s_axis_rq_seq_num_valid_0,
    input  wire [RQ_SEQ_NUM_WIDTH-1:0]                               s_axis_rq_seq_num_1,
    input  wire                                                      s_axis_rq_seq_num_valid_1,
    output wire [9:0]                                                cfg_mgmt_addr,
    output wire [7:0]                                                cfg_mgmt_function_number,
    output wire                                                      cfg_mgmt_write,
    output wire [31:0]                                               cfg_mgmt_write_data,
    output wire [3:0]                                                cfg_mgmt_byte_enable,
    output wire                                                      cfg_mgmt_read,
    input  wire [31:0]                                               cfg_mgmt_read_data,
    input  wire                                                      cfg_mgmt_read_write_done,
    input  wire [2:0]                                                cfg_max_payload,
    input  wire [2:0]                                                cfg_max_read_req,
    input  wire [7:0]                                                cfg_fc_ph,
    input  wire [11:0]                                               cfg_fc_pd,
    input  wire [7:0]                                                cfg_fc_nph,
    input  wire [11:0]                                               cfg_fc_npd,
    input  wire [7:0]                                                cfg_fc_cplh,
    input  wire [11:0]                                               cfg_fc_cpld,
    output wire [2:0]                                                cfg_fc_sel,
    input  wire [3:0]                                                cfg_interrupt_msi_enable,
    input  wire [7:0]                                                cfg_interrupt_msi_vf_enable,
    input  wire [11:0]                                               cfg_interrupt_msi_mmenable,
    input  wire                                                      cfg_interrupt_msi_mask_update,
    input  wire [31:0]                                               cfg_interrupt_msi_data,
    output wire [3:0]                                                cfg_interrupt_msi_select,
    output wire [31:0]                                               cfg_interrupt_msi_int,
    output wire [31:0]                                               cfg_interrupt_msi_pending_status,
    output wire                                                      cfg_interrupt_msi_pending_status_data_enable,
    output wire [3:0]                                                cfg_interrupt_msi_pending_status_function_num,
    input  wire                                                      cfg_interrupt_msi_sent,
    input  wire                                                      cfg_interrupt_msi_fail,
    input  wire [3:0]                                                cfg_interrupt_msix_enable,
    input  wire [3:0]                                                cfg_interrupt_msix_mask,
    input  wire [251:0]                                              cfg_interrupt_msix_vf_enable,
    input  wire [251:0]                                              cfg_interrupt_msix_vf_mask,
    output wire [63:0]                                               cfg_interrupt_msix_address,
    output wire [31:0]                                               cfg_interrupt_msix_data,
    output wire                                                      cfg_interrupt_msix_int,
    output wire [1:0]                                                cfg_interrupt_msix_vec_pending,
    input  wire                                                      cfg_interrupt_msix_vec_pending_status,
    input  wire                                                      cfg_interrupt_msix_sent,
    input  wire                                                      cfg_interrupt_msix_fail,
    output wire [2:0]                                                cfg_interrupt_msi_attr,
    output wire                                                      cfg_interrupt_msi_tph_present,
    output wire [1:0]                                                cfg_interrupt_msi_tph_type,
    output wire [8:0]                                                cfg_interrupt_msi_tph_st_tag,
    output wire [7:0]                                                cfg_interrupt_msi_function_number,
    output wire [TLP_DATA_WIDTH-1:0]                                 rx_req_tlp_data,
    output wire [TLP_STRB_WIDTH-1:0]                                 rx_req_tlp_strb,
    output wire [TLP_SEG_COUNT*TLP_HDR_WIDTH-1:0]                    rx_req_tlp_hdr,
    output wire [TLP_SEG_COUNT*3-1:0]                                rx_req_tlp_bar_id,
    output wire [TLP_SEG_COUNT*8-1:0]                                rx_req_tlp_func_num,
    output wire [TLP_SEG_COUNT-1:0]                                  rx_req_tlp_valid,
    output wire [TLP_SEG_COUNT-1:0]                                  rx_req_tlp_sop,
    output wire [TLP_SEG_COUNT-1:0]                                  rx_req_tlp_eop,
    input  wire                                                      rx_req_tlp_ready,
    output wire [TLP_DATA_WIDTH-1:0]                                 rx_cpl_tlp_data,
    output wire [TLP_STRB_WIDTH-1:0]                                 rx_cpl_tlp_strb,
    output wire [TLP_SEG_COUNT*TLP_HDR_WIDTH-1:0]                    rx_cpl_tlp_hdr,
    output wire [TLP_SEG_COUNT*4-1:0]                                rx_cpl_tlp_error,
    output wire [TLP_SEG_COUNT-1:0]                                  rx_cpl_tlp_valid,
    output wire [TLP_SEG_COUNT-1:0]                                  rx_cpl_tlp_sop,
    output wire [TLP_SEG_COUNT-1:0]                                  rx_cpl_tlp_eop,
    input  wire                                                      rx_cpl_tlp_ready,
    input  wire [TLP_SEG_COUNT*TLP_HDR_WIDTH-1:0]                    tx_rd_req_tlp_hdr,
    input  wire [TLP_SEG_COUNT*TX_SEQ_NUM_WIDTH-1:0]                 tx_rd_req_tlp_seq,
    input  wire [TLP_SEG_COUNT-1:0]                                  tx_rd_req_tlp_valid,
    input  wire [TLP_SEG_COUNT-1:0]                                  tx_rd_req_tlp_sop,
    input  wire [TLP_SEG_COUNT-1:0]                                  tx_rd_req_tlp_eop,
    output wire                                                      tx_rd_req_tlp_ready,
    output wire [TX_SEQ_NUM_COUNT*TX_SEQ_NUM_WIDTH-1:0]              m_axis_rd_req_tx_seq_num,
    output wire [TX_SEQ_NUM_COUNT-1:0]                               m_axis_rd_req_tx_seq_num_valid,
    input  wire [TLP_DATA_WIDTH-1:0]                                 tx_wr_req_tlp_data,
    input  wire [TLP_STRB_WIDTH-1:0]                                 tx_wr_req_tlp_strb,
    input  wire [TLP_SEG_COUNT*TLP_HDR_WIDTH-1:0]                    tx_wr_req_tlp_hdr,
    input  wire [TLP_SEG_COUNT*TX_SEQ_NUM_WIDTH-1:0]                 tx_wr_req_tlp_seq,
    input  wire [TLP_SEG_COUNT-1:0]                                  tx_wr_req_tlp_valid,
    input  wire [TLP_SEG_COUNT-1:0]                                  tx_wr_req_tlp_sop,
    input  wire [TLP_SEG_COUNT-1:0]                                  tx_wr_req_tlp_eop,
    output wire                                                      tx_wr_req_tlp_ready,
    output wire [TX_SEQ_NUM_COUNT*TX_SEQ_NUM_WIDTH-1:0]              m_axis_wr_req_tx_seq_num,
    output wire [TX_SEQ_NUM_COUNT-1:0]                               m_axis_wr_req_tx_seq_num_valid,
    input  wire [TLP_DATA_WIDTH-1:0]                                 tx_cpl_tlp_data,
    input  wire [TLP_STRB_WIDTH-1:0]                                 tx_cpl_tlp_strb,
    input  wire [TLP_SEG_COUNT*TLP_HDR_WIDTH-1:0]                    tx_cpl_tlp_hdr,
    input  wire [TLP_SEG_COUNT-1:0]                                  tx_cpl_tlp_valid,
    input  wire [TLP_SEG_COUNT-1:0]                                  tx_cpl_tlp_sop,
    input  wire [TLP_SEG_COUNT-1:0]                                  tx_cpl_tlp_eop,
    output wire                                                      tx_cpl_tlp_ready,
    input  wire [31:0]                                               tx_msix_wr_req_tlp_data,
    input  wire                                                      tx_msix_wr_req_tlp_strb,
    input  wire [TLP_HDR_WIDTH-1:0]                                  tx_msix_wr_req_tlp_hdr,
    input  wire                                                      tx_msix_wr_req_tlp_valid,
    input  wire                                                      tx_msix_wr_req_tlp_sop,
    input  wire                                                      tx_msix_wr_req_tlp_eop,
    output wire                                                      tx_msix_wr_req_tlp_ready,
    output wire [7:0]                                                tx_fc_ph_av,
    output wire [11:0]                                               tx_fc_pd_av,
    output wire [7:0]                                                tx_fc_nph_av,
    output wire [11:0]                                               tx_fc_npd_av,
    output wire [7:0]                                                tx_fc_cplh_av,
    output wire [11:0]                                               tx_fc_cpld_av,
    output wire [F_COUNT-1:0]                                        ext_tag_enable,
    output wire [F_COUNT*3-1:0]                                      max_read_request_size,
    output wire [F_COUNT*3-1:0]                                      max_payload_size,
    output wire [F_COUNT-1:0]                                        msix_enable,
    output wire [F_COUNT-1:0]                                        msix_mask,
    input  wire [MSI_COUNT-1:0]                                      msi_irq,
    output wire [1:0]                                    sts_cq_poisoned_tlp,
    output wire                                          sts_cq_poisoned_seen
);

wire [AXIS_PCIE_DATA_WIDTH-1:0] us_rc_tdata;
wire [AXIS_PCIE_KEEP_WIDTH-1:0] us_rc_tkeep;
wire                            us_rc_tvalid;
wire                            us_rc_tready;
wire                            us_rc_tlast;
wire [AXIS_PCIE_RC_USER_WIDTH-1:0] us_rc_tuser;

wire [AXIS_PCIE_DATA_WIDTH-1:0] us_rq_tdata;
wire [AXIS_PCIE_KEEP_WIDTH-1:0] us_rq_tkeep;
wire                            us_rq_tvalid;
wire                            us_rq_tready;
wire                            us_rq_tlast;
wire [AXIS_PCIE_RQ_USER_WIDTH-1:0] us_rq_tuser;

wire [AXIS_PCIE_DATA_WIDTH-1:0] us_cq_tdata;
wire [AXIS_PCIE_KEEP_WIDTH-1:0] us_cq_tkeep;
wire                            us_cq_tvalid;
wire                            us_cq_tready;
wire                            us_cq_tlast;
wire [AXIS_PCIE_CQ_USER_WIDTH-1:0] us_cq_tuser;

wire [AXIS_PCIE_DATA_WIDTH-1:0] us_cc_tdata;
wire [AXIS_PCIE_KEEP_WIDTH-1:0] us_cc_tkeep;
wire                            us_cc_tvalid;
wire                            us_cc_tready;
wire                            us_cc_tlast;
wire [AXIS_PCIE_CC_USER_WIDTH-1:0] us_cc_tuser;

pcie_versal_adapt #(
    .DATA_W(AXIS_PCIE_DATA_WIDTH),
    .KEEP_W(AXIS_PCIE_KEEP_WIDTH),
    .CPM5_RQ_USER_W(CPM5_RQ_USER_WIDTH),
    .CPM5_CQ_USER_W(CPM5_CQ_USER_WIDTH),
    .US_RQ_USER_W(AXIS_PCIE_RQ_USER_WIDTH),
    .US_CQ_USER_W(AXIS_PCIE_CQ_USER_WIDTH),
    .RC_USER_W(AXIS_PCIE_RC_USER_WIDTH),
    .CC_USER_W(AXIS_PCIE_CC_USER_WIDTH)
)
adapt_inst (
    .clk(clk),
    .rst(rst),

    .us_rq_tdata(us_rq_tdata),
    .us_rq_tkeep(us_rq_tkeep),
    .us_rq_tvalid(us_rq_tvalid),
    .us_rq_tready(us_rq_tready),
    .us_rq_tlast(us_rq_tlast),
    .us_rq_tuser(us_rq_tuser),
    .cpm_rq_tdata(m_axis_rq_tdata),
    .cpm_rq_tkeep(m_axis_rq_tkeep),
    .cpm_rq_tvalid(m_axis_rq_tvalid),
    .cpm_rq_tready(m_axis_rq_tready),
    .cpm_rq_tlast(m_axis_rq_tlast),
    .cpm_rq_tuser(m_axis_rq_tuser),

    .cpm_rc_tdata(s_axis_rc_tdata),
    .cpm_rc_tkeep(s_axis_rc_tkeep),
    .cpm_rc_tvalid(s_axis_rc_tvalid),
    .cpm_rc_tready(s_axis_rc_tready),
    .cpm_rc_tlast(s_axis_rc_tlast),
    .cpm_rc_tuser(s_axis_rc_tuser),
    .us_rc_tdata(us_rc_tdata),
    .us_rc_tkeep(us_rc_tkeep),
    .us_rc_tvalid(us_rc_tvalid),
    .us_rc_tready(us_rc_tready),
    .us_rc_tlast(us_rc_tlast),
    .us_rc_tuser(us_rc_tuser),

    .cpm_cq_tdata(s_axis_cq_tdata),
    .cpm_cq_tkeep(s_axis_cq_tkeep),
    .cpm_cq_tvalid(s_axis_cq_tvalid),
    .cpm_cq_tready(s_axis_cq_tready),
    .cpm_cq_tlast(s_axis_cq_tlast),
    .cpm_cq_tuser(s_axis_cq_tuser),
    .us_cq_tdata(us_cq_tdata),
    .us_cq_tkeep(us_cq_tkeep),
    .us_cq_tvalid(us_cq_tvalid),
    .us_cq_tready(us_cq_tready),
    .us_cq_tlast(us_cq_tlast),
    .us_cq_tuser(us_cq_tuser),

    .us_cc_tdata(us_cc_tdata),
    .us_cc_tkeep(us_cc_tkeep),
    .us_cc_tvalid(us_cc_tvalid),
    .us_cc_tready(us_cc_tready),
    .us_cc_tlast(us_cc_tlast),
    .us_cc_tuser(us_cc_tuser),
    .cpm_cc_tdata(m_axis_cc_tdata),
    .cpm_cc_tkeep(m_axis_cc_tkeep),
    .cpm_cc_tvalid(m_axis_cc_tvalid),
    .cpm_cc_tready(m_axis_cc_tready),
    .cpm_cc_tlast(m_axis_cc_tlast),
    .cpm_cc_tuser(m_axis_cc_tuser),

    .sts_cq_poisoned_tlp(sts_cq_poisoned_tlp),
    .sts_cq_poisoned_seen(sts_cq_poisoned_seen)
);

pcie_us_if #(
    .AXIS_PCIE_DATA_WIDTH(AXIS_PCIE_DATA_WIDTH),
    .AXIS_PCIE_KEEP_WIDTH(AXIS_PCIE_KEEP_WIDTH),
    .AXIS_PCIE_RC_USER_WIDTH(AXIS_PCIE_RC_USER_WIDTH),
    .AXIS_PCIE_RQ_USER_WIDTH(AXIS_PCIE_RQ_USER_WIDTH),
    .AXIS_PCIE_CQ_USER_WIDTH(AXIS_PCIE_CQ_USER_WIDTH),
    .AXIS_PCIE_CC_USER_WIDTH(AXIS_PCIE_CC_USER_WIDTH),
    .RC_STRADDLE(RC_STRADDLE),
    .RQ_STRADDLE(RQ_STRADDLE),
    .CQ_STRADDLE(CQ_STRADDLE),
    .CC_STRADDLE(CC_STRADDLE),
    .RQ_SEQ_NUM_WIDTH(RQ_SEQ_NUM_WIDTH),
    .TLP_DATA_WIDTH(TLP_DATA_WIDTH),
    .TLP_STRB_WIDTH(TLP_STRB_WIDTH),
    .TLP_HDR_WIDTH(TLP_HDR_WIDTH),
    .TLP_SEG_COUNT(TLP_SEG_COUNT),
    .TX_SEQ_NUM_COUNT(TX_SEQ_NUM_COUNT),
    .TX_SEQ_NUM_WIDTH(TX_SEQ_NUM_WIDTH),
    .PF_COUNT(PF_COUNT),
    .VF_COUNT(VF_COUNT),
    .F_COUNT(F_COUNT),
    .READ_EXT_TAG_ENABLE(READ_EXT_TAG_ENABLE),
    .READ_MAX_READ_REQ_SIZE(READ_MAX_READ_REQ_SIZE),
    .READ_MAX_PAYLOAD_SIZE(READ_MAX_PAYLOAD_SIZE),
    .MSIX_ENABLE(MSIX_ENABLE),
    .MSI_ENABLE(MSI_ENABLE),
    .MSI_COUNT(MSI_COUNT)
)
pcie_us_if_inst (
    .clk(clk),
    .rst(rst),
    .s_axis_rc_tdata(us_rc_tdata),
    .s_axis_rc_tkeep(us_rc_tkeep),
    .s_axis_rc_tvalid(us_rc_tvalid),
    .s_axis_rc_tready(us_rc_tready),
    .s_axis_rc_tlast(us_rc_tlast),
    .s_axis_rc_tuser(us_rc_tuser),
    .m_axis_rq_tdata(us_rq_tdata),
    .m_axis_rq_tkeep(us_rq_tkeep),
    .m_axis_rq_tvalid(us_rq_tvalid),
    .m_axis_rq_tready(us_rq_tready),
    .m_axis_rq_tlast(us_rq_tlast),
    .m_axis_rq_tuser(us_rq_tuser),
    .s_axis_cq_tdata(us_cq_tdata),
    .s_axis_cq_tkeep(us_cq_tkeep),
    .s_axis_cq_tvalid(us_cq_tvalid),
    .s_axis_cq_tready(us_cq_tready),
    .s_axis_cq_tlast(us_cq_tlast),
    .s_axis_cq_tuser(us_cq_tuser),
    .m_axis_cc_tdata(us_cc_tdata),
    .m_axis_cc_tkeep(us_cc_tkeep),
    .m_axis_cc_tvalid(us_cc_tvalid),
    .m_axis_cc_tready(us_cc_tready),
    .m_axis_cc_tlast(us_cc_tlast),
    .m_axis_cc_tuser(us_cc_tuser),
    .s_axis_rq_seq_num_0(s_axis_rq_seq_num_0),
    .s_axis_rq_seq_num_valid_0(s_axis_rq_seq_num_valid_0),
    .s_axis_rq_seq_num_1(s_axis_rq_seq_num_1),
    .s_axis_rq_seq_num_valid_1(s_axis_rq_seq_num_valid_1),
    .cfg_mgmt_addr(cfg_mgmt_addr),
    .cfg_mgmt_function_number(cfg_mgmt_function_number),
    .cfg_mgmt_write(cfg_mgmt_write),
    .cfg_mgmt_write_data(cfg_mgmt_write_data),
    .cfg_mgmt_byte_enable(cfg_mgmt_byte_enable),
    .cfg_mgmt_read(cfg_mgmt_read),
    .cfg_mgmt_read_data(cfg_mgmt_read_data),
    .cfg_mgmt_read_write_done(cfg_mgmt_read_write_done),
    .cfg_max_payload(cfg_max_payload),
    .cfg_max_read_req(cfg_max_read_req),
    .cfg_fc_ph(cfg_fc_ph),
    .cfg_fc_pd(cfg_fc_pd),
    .cfg_fc_nph(cfg_fc_nph),
    .cfg_fc_npd(cfg_fc_npd),
    .cfg_fc_cplh(cfg_fc_cplh),
    .cfg_fc_cpld(cfg_fc_cpld),
    .cfg_fc_sel(cfg_fc_sel),
    .cfg_interrupt_msi_enable(cfg_interrupt_msi_enable),
    .cfg_interrupt_msi_vf_enable(cfg_interrupt_msi_vf_enable),
    .cfg_interrupt_msi_mmenable(cfg_interrupt_msi_mmenable),
    .cfg_interrupt_msi_mask_update(cfg_interrupt_msi_mask_update),
    .cfg_interrupt_msi_data(cfg_interrupt_msi_data),
    .cfg_interrupt_msi_select(cfg_interrupt_msi_select),
    .cfg_interrupt_msi_int(cfg_interrupt_msi_int),
    .cfg_interrupt_msi_pending_status(cfg_interrupt_msi_pending_status),
    .cfg_interrupt_msi_pending_status_data_enable(cfg_interrupt_msi_pending_status_data_enable),
    .cfg_interrupt_msi_pending_status_function_num(cfg_interrupt_msi_pending_status_function_num),
    .cfg_interrupt_msi_sent(cfg_interrupt_msi_sent),
    .cfg_interrupt_msi_fail(cfg_interrupt_msi_fail),
    .cfg_interrupt_msix_enable(cfg_interrupt_msix_enable),
    .cfg_interrupt_msix_mask(cfg_interrupt_msix_mask),
    .cfg_interrupt_msix_vf_enable(cfg_interrupt_msix_vf_enable),
    .cfg_interrupt_msix_vf_mask(cfg_interrupt_msix_vf_mask),
    .cfg_interrupt_msix_address(cfg_interrupt_msix_address),
    .cfg_interrupt_msix_data(cfg_interrupt_msix_data),
    .cfg_interrupt_msix_int(cfg_interrupt_msix_int),
    .cfg_interrupt_msix_vec_pending(cfg_interrupt_msix_vec_pending),
    .cfg_interrupt_msix_vec_pending_status(cfg_interrupt_msix_vec_pending_status),
    .cfg_interrupt_msix_sent(cfg_interrupt_msix_sent),
    .cfg_interrupt_msix_fail(cfg_interrupt_msix_fail),
    .cfg_interrupt_msi_attr(cfg_interrupt_msi_attr),
    .cfg_interrupt_msi_tph_present(cfg_interrupt_msi_tph_present),
    .cfg_interrupt_msi_tph_type(cfg_interrupt_msi_tph_type),
    .cfg_interrupt_msi_tph_st_tag(cfg_interrupt_msi_tph_st_tag),
    .cfg_interrupt_msi_function_number(cfg_interrupt_msi_function_number),
    .rx_req_tlp_data(rx_req_tlp_data),
    .rx_req_tlp_strb(rx_req_tlp_strb),
    .rx_req_tlp_hdr(rx_req_tlp_hdr),
    .rx_req_tlp_bar_id(rx_req_tlp_bar_id),
    .rx_req_tlp_func_num(rx_req_tlp_func_num),
    .rx_req_tlp_valid(rx_req_tlp_valid),
    .rx_req_tlp_sop(rx_req_tlp_sop),
    .rx_req_tlp_eop(rx_req_tlp_eop),
    .rx_req_tlp_ready(rx_req_tlp_ready),
    .rx_cpl_tlp_data(rx_cpl_tlp_data),
    .rx_cpl_tlp_strb(rx_cpl_tlp_strb),
    .rx_cpl_tlp_hdr(rx_cpl_tlp_hdr),
    .rx_cpl_tlp_error(rx_cpl_tlp_error),
    .rx_cpl_tlp_valid(rx_cpl_tlp_valid),
    .rx_cpl_tlp_sop(rx_cpl_tlp_sop),
    .rx_cpl_tlp_eop(rx_cpl_tlp_eop),
    .rx_cpl_tlp_ready(rx_cpl_tlp_ready),
    .tx_rd_req_tlp_hdr(tx_rd_req_tlp_hdr),
    .tx_rd_req_tlp_seq(tx_rd_req_tlp_seq),
    .tx_rd_req_tlp_valid(tx_rd_req_tlp_valid),
    .tx_rd_req_tlp_sop(tx_rd_req_tlp_sop),
    .tx_rd_req_tlp_eop(tx_rd_req_tlp_eop),
    .tx_rd_req_tlp_ready(tx_rd_req_tlp_ready),
    .m_axis_rd_req_tx_seq_num(m_axis_rd_req_tx_seq_num),
    .m_axis_rd_req_tx_seq_num_valid(m_axis_rd_req_tx_seq_num_valid),
    .tx_wr_req_tlp_data(tx_wr_req_tlp_data),
    .tx_wr_req_tlp_strb(tx_wr_req_tlp_strb),
    .tx_wr_req_tlp_hdr(tx_wr_req_tlp_hdr),
    .tx_wr_req_tlp_seq(tx_wr_req_tlp_seq),
    .tx_wr_req_tlp_valid(tx_wr_req_tlp_valid),
    .tx_wr_req_tlp_sop(tx_wr_req_tlp_sop),
    .tx_wr_req_tlp_eop(tx_wr_req_tlp_eop),
    .tx_wr_req_tlp_ready(tx_wr_req_tlp_ready),
    .m_axis_wr_req_tx_seq_num(m_axis_wr_req_tx_seq_num),
    .m_axis_wr_req_tx_seq_num_valid(m_axis_wr_req_tx_seq_num_valid),
    .tx_cpl_tlp_data(tx_cpl_tlp_data),
    .tx_cpl_tlp_strb(tx_cpl_tlp_strb),
    .tx_cpl_tlp_hdr(tx_cpl_tlp_hdr),
    .tx_cpl_tlp_valid(tx_cpl_tlp_valid),
    .tx_cpl_tlp_sop(tx_cpl_tlp_sop),
    .tx_cpl_tlp_eop(tx_cpl_tlp_eop),
    .tx_cpl_tlp_ready(tx_cpl_tlp_ready),
    .tx_msix_wr_req_tlp_data(tx_msix_wr_req_tlp_data),
    .tx_msix_wr_req_tlp_strb(tx_msix_wr_req_tlp_strb),
    .tx_msix_wr_req_tlp_hdr(tx_msix_wr_req_tlp_hdr),
    .tx_msix_wr_req_tlp_valid(tx_msix_wr_req_tlp_valid),
    .tx_msix_wr_req_tlp_sop(tx_msix_wr_req_tlp_sop),
    .tx_msix_wr_req_tlp_eop(tx_msix_wr_req_tlp_eop),
    .tx_msix_wr_req_tlp_ready(tx_msix_wr_req_tlp_ready),
    .tx_fc_ph_av(tx_fc_ph_av),
    .tx_fc_pd_av(tx_fc_pd_av),
    .tx_fc_nph_av(tx_fc_nph_av),
    .tx_fc_npd_av(tx_fc_npd_av),
    .tx_fc_cplh_av(tx_fc_cplh_av),
    .tx_fc_cpld_av(tx_fc_cpld_av),
    .ext_tag_enable(ext_tag_enable),
    .max_read_request_size(max_read_request_size),
    .max_payload_size(max_payload_size),
    .msix_enable(msix_enable),
    .msix_mask(msix_mask),
    .msi_irq(msi_irq)
);

endmodule

`resetall
